language: java
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
notifications:
  email:
    recipients:
    - cedar-core-developers@lists.stanford.edu
    on_success: never
    on_failure: always
install: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=false clean deploy --settings .m2/travis-settings.xml'
script: '[ ${TRAVIS_PULL_REQUEST} = ''false'' ] && mvn -DskipTests=true clean --settings .m2/travis-settings.xml'
env:
  global:
  - secure: MtEIkzgnAGvXAsSUI3PR0labEyrwlmbbzaiWRxWQFnuBNFOOQgerqCbwpxHY3jb+ogpthFrxhDOZTVWZuPACjTrfcGV02PO4w92L9OI+W9uzgKOE5rMcyvw9/1FanDj0NPFqCI2yukvvbBAEEO+/+FEvEErB1Bkx49C8KVNK8rSD3cSp8Nkh1c4hSWqnqrHdqZZDTl5uueWt/3eK+4FTxHPY8BfRY3KFCJO/KNB3OA9l4dehVCcnhAItQouuPkpsNV9Tke64X2hCnWcFHdiu9p0k5rC9dGurhgf9oQyWmY51Gjq4VLTke/oIO7IkXnWdKTfUQMgVnDoLvy/hIrH8VlwGzuwfU9nahJaW0Y1YLETOih2RAqcKtcKD1Epsl44gg89QT7rVRv9aio3MjxgDxI20T01jkgBs9nxUrKOhnFw5Ow7G7wM7n5Qozt5E7ty1GKrw0GmTEjEbczqEL5Aeid3DlDQTf7f+sezovZXPjAc23TLsVWXQXHRt8OSMm4DGU28JxnuEXjD/BeUQHgBSdFbkGj0N5L9+84ltPjizWUgH4T0NBRsOb89AErLDAGY8tZ9Wl205TZcyR3YtU+7WI1f2aEmO4hkDU3G0Rv5sDu++U7lfC5pce38IWsRKEKzTUxMzLgUqMslm4OuvTXK+C3SL6j7S7jWj9rtj/xZIhMo=
  - secure: N0+16rmWEwyqIZtk2zTr1nsTUtAYiqu6QuYFoZNrAOPOgUESZJ9/BsiDWE0KZ4lotUIgBxHMHFtAwtVPtRXF9rybbQwk7Fdp0HQsUfor1cQ56iZ9WJetWH17KM3WTmGHzfN9iyVt4xH9BzbDFNaLVuqno60rHhIbBaKz3gv7kU42FSWcmOeYtLxa87RcCWOjy90pwQSn4a66d9rj/YjLUpohNfMZVnFt8VmZ520DxlGZ0JqptYnca4A2wykfZWCUpEHJ/VNa3U6PnOYniDRzwjjBYfW64/s9GfFq0dBpSooU2YreoLCFtAI1MMM67olF3vJkT+B+R1LjCuEuX1gpPJkPnM6ZCaxDMOIt7iQaLQ6r+AqdNynjzK3UcPEn+r6a/oB6uo/LsCsbV56CSzJ2dwtMakUbPlb4/d7vv8Jfj9TqpvR9LIVvW0rw5RcStrdFo6omOFHSdc7s06oiDqkgx47y7MCAUQvpCBd6cqEmCTUc1kmNiZ7TjgKl7RlJr88lnxvs3Nr+AEJ6KQL3MTdFGs3o9VN+mLKgASpZdjZEd7BSa7XzBdUF5wtIBzot3SyCdJtoIsZhqezoC+5lit5o3QRB7XiayJdjojkSt5UVIZrTw2AXWmnVDymxtm92Lif/RszZgfG0CdNhGlqu2tWu7UMuLErY8nqrWqNJo44dsuM=
